name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Gradle Testing Assignment
      id: gradle-testing-assignment
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Gradle Testing Assignment
        setup-command: ''
        command: gradle test --tests InsertionSortTest
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRADLE-TESTING-ASSIGNMENT_RESULTS: "${{steps.gradle-testing-assignment.outputs.result}}"
      with:
        runners: gradle-testing-assignment
